export function buildCustomerDashboardRouteBindings({
  accountIdentityInitials,
  accountIdentityName,
  accountIdentityContact,
  accountPanel,
  hasSavedCustomerDetails,
  maskedSavedCustomerPreview,
  activeCustomerOrders,
  activeCustomerOrderCount,
  trackedCustomerActivity,
  customerTrackLoadingReference,
  customerTrackError,
  accountOrderActionReference,
  accountAddressActionId,
  handleLoadAccountPanel,
  handleTrackCustomerReference,
  handleMarkNotificationRead,
  handleMarkAllNotificationsRead,
  handleStorefrontSignOut,
  openBusinessRegistrationFlow,
  requestDgfyBusinessSecurityCode,
  handleAcceptDgfyCompanyInvitation,
  handleRejectDgfyCompanyInvitation,
  handleLeaveDgfyCompany,
  switchDgfyCompanyFromStorefront,
  clearSavedCustomerDetailsForDevice,
  useAccountAddressForCheckout,
  handleSaveAccountAddress,
  handleDeleteAccountAddress,
  handleSetDefaultAccountAddress,
  renderAddressPinEditor,
  openStorefrontFromAccountEntry,
  submitAccountReviewFromDashboard,
  handleOpenBusinessInventory,
  handleOpenBusinessPos,
  resolveStorefrontMetaForAccountEntry,
  withAssetOrigin
}) {
  return {
    state: {
      accountIdentityInitials,
      accountIdentityName,
      accountIdentityContact,
      accountPanel,
      hasSavedCustomerDetails,
      maskedSavedCustomerPreview,
      activeCustomerOrders,
      activeCustomerOrderCount,
      trackedCustomerActivity,
      customerTrackLoadingReference,
      customerTrackError,
      accountOrderActionReference,
      accountAddressActionId
    },
    actions: {
      handleLoadAccountPanel,
      handleTrackCustomerReference,
      handleMarkNotificationRead,
      handleMarkAllNotificationsRead,
      handleStorefrontSignOut,
      openBusinessRegistrationFlow,
      requestDgfyBusinessSecurityCode,
      handleAcceptDgfyCompanyInvitation,
      handleRejectDgfyCompanyInvitation,
      handleLeaveDgfyCompany,
      switchDgfyCompanyFromStorefront,
      clearSavedCustomerDetailsForDevice,
      useAccountAddressForCheckout,
      handleSaveAccountAddress,
      handleDeleteAccountAddress,
      handleSetDefaultAccountAddress,
      renderAddressPinEditor,
      openStorefrontFromAccountEntry,
      submitAccountReviewFromDashboard,
      handleOpenBusinessInventory,
      handleOpenBusinessPos
    },
    resolvers: {
      resolveStorefrontMetaForAccountEntry,
      withAssetOrigin
    }
  };
}

export default buildCustomerDashboardRouteBindings;
