export function useSimpleCheckoutRouteProps({
  applySavedDeliveryLocation,
  canAddPinnedLocation = false,
  canUseGuestCheckoutFlow = false,
  cart = [],
  cartCount = 0,
  cartImageErrors,
  checkoutError = '',
  checkoutLoading = false,
  checkoutResult = null,
  customerAddress = '',
  customerPin = null,
  deliveryLocationAction = 'saved',
  deliveryLocationDisplayAddress = '',
  deliverySavedLocations = [],
  DropdownComponent,
  fnbPaymentType = 'cash',
  fnbScheduleMode = 'asap',
  fnbScheduledFor = '',
  fnbSpecialInstructions = '',
  goStoreCatalogPage,
  handleAddPinnedLocation,
  handleCheckout,
  handleDownloadCheckoutImage,
  handlePaymentTypeChange,
  handlePinMyLocation,
  handleQuote,
  handleRemoveDeliveryAddress,
  handleSetDefaultDeliveryAddress,
  isDeliveryOrder = false,
  isDesktopCheckout = false,
  isDgfyCustomerSignedIn = false,
  isMobileViewport = false,
  money,
  orderMethod = 'delivery',
  pinLocationError = '',
  pinLocationLoading = false,
  promoDiscountSummaryRow = null,
  quoteError = '',
  quoteResult = null,
  renderAccountOwnedIdentitySummary,
  renderGuestCheckoutEntry,
  renderGuestIdentityFields,
  renderPromoCodePanel,
  renderStorefrontClosedNotice,
  requireQuoteForCheckout = false,
  selectedLocation = null,
  selectedLocationId = null,
  selectedSavedLocationId = '',
  selectedStore = null,
  servicesBodyFont,
  servicesDisplayFont,
  setCartImageErrors,
  setCheckoutResult,
  setCustomerAddress,
  setCustomerPin,
  setDeliveryLocationAction,
  setFnbScheduledFor,
  setFnbScheduleMode,
  setFnbSpecialInstructions,
  setOrderMethod,
  setPinLocationError,
  setResolvedDeliveryAddress,
  setSelectedLocationId,
  setSelectedSavedLocationId,
  setShowExpandedDeliveryMap,
  setShowSimpleMobileAddressModal,
  setShowSimpleMobileOrderSummary,
  setSimpleOrderStep,
  showExpandedDeliveryMap = false,
  showSimpleMobileAddressModal = false,
  showSimpleMobileOrderSummary = false,
  simpleCheckoutAllowed = false,
  simpleCustomerStepComplete = false,
  simpleHasCustomerIdentity = false,
  simpleHasPrimaryIdentityContact = false,
  simpleOrderMethodOptions = [],
  simpleOrderStep = 1,
  simpleStepOneReady = false,
  storefrontClosedByHours = false,
  storeLocations = [],
  totalsForDisplay,
  withAssetOrigin
}) {
  return {
    canAddPinnedLocation,
    canUseGuestCheckoutFlow,
    cart,
    cartCount,
    cartImageErrors,
    checkoutError,
    checkoutLoading,
    checkoutResult,
    customerAddress,
    customerPin,
    deliveryLocationAction,
    deliveryLocationDisplayAddress,
    deliverySavedLocations,
    DropdownComponent,
    fnbPaymentType,
    fnbScheduleMode,
    fnbScheduledFor,
    fnbSpecialInstructions,
    isDeliveryOrder,
    isDesktopCheckout,
    isDgfyCustomerSignedIn,
    isMobileViewport,
    money,
    orderMethod,
    pinLocationError,
    pinLocationLoading,
    promoDiscountSummaryRow,
    quoteError,
    quoteResult,
    renderAccountOwnedIdentitySummary,
    renderGuestCheckoutEntry,
    renderGuestIdentityFields,
    renderPromoCodePanel,
    renderStorefrontClosedNotice,
    requireQuoteForCheckout,
    selectedLocation,
    selectedLocationId,
    selectedSavedLocationId,
    selectedStore,
    servicesBodyFont,
    servicesDisplayFont,
    setDeliveryLocationAction,
    setSelectedSavedLocationId,
    setShowExpandedDeliveryMap,
    setShowSimpleMobileAddressModal,
    setShowSimpleMobileOrderSummary,
    showExpandedDeliveryMap,
    showSimpleMobileAddressModal,
    showSimpleMobileOrderSummary,
    simpleCheckoutAllowed,
    simpleCustomerStepComplete,
    simpleHasCustomerIdentity,
    simpleHasPrimaryIdentityContact,
    simpleOrderMethodOptions,
    simpleOrderStep,
    simpleStepOneReady,
    storefrontClosedByHours,
    storeLocations,
    totalsForDisplay,
    withAssetOrigin,
    onBackToCatalog: goStoreCatalogPage,
    onCheckout: handleCheckout,
    onCustomerAddressChange: setCustomerAddress,
    onDownloadCheckoutImage: handleDownloadCheckoutImage,
    onOrderMethodChange: (nextOrderMethod) => {
      setOrderMethod(nextOrderMethod);
      setPinLocationError('');
    },
    onAddPinnedLocation: handleAddPinnedLocation,
    onCloseExpandedMap: () => setShowExpandedDeliveryMap(false),
    onImageError: (itemId) => {
      const normalizedLineItemId = Number(itemId);
      if (!Number.isFinite(normalizedLineItemId)) return;
      setCartImageErrors((previous) => new Set([...previous, normalizedLineItemId]));
    },
    onOpenExpandedMap: () => setShowExpandedDeliveryMap(true),
    onPaymentTypeChange: handlePaymentTypeChange,
    onPinChange: (nextPin) => {
      setDeliveryLocationAction('map');
      setSelectedSavedLocationId('');
      setCustomerPin(nextPin);
    },
    onPinClear: () => setCustomerPin(null),
    onPinMyLocation: handlePinMyLocation,
    onQuote: handleQuote,
    onRemoveDeliveryAddress: handleRemoveDeliveryAddress,
    onScheduleModeChange: (nextMode) => {
      setFnbScheduleMode(nextMode);
      if (nextMode === 'asap') setFnbScheduledFor('');
    },
    onScheduledForChange: (nextScheduledFor) => {
      setFnbScheduledFor(nextScheduledFor);
      setFnbScheduleMode('schedule');
    },
    onSelectAddress: (location) => {
      applySavedDeliveryLocation(location);
      if (typeof handleSetDefaultDeliveryAddress === 'function' && !location.isDefault) {
        handleSetDefaultDeliveryAddress(location);
      }
    },
    onSelectedLocationChange: setSelectedLocationId,
    onSetCheckoutResult: setCheckoutResult,
    onSetDefaultDeliveryAddress: handleSetDefaultDeliveryAddress,
    onSetSimpleOrderStep: setSimpleOrderStep,
    onSpecialInstructionsChange: setFnbSpecialInstructions,
    onStartMapPin: () => {
      setDeliveryLocationAction('map');
      setSelectedSavedLocationId('');
      setPinLocationError('');
      setResolvedDeliveryAddress('');
      setCustomerAddress('');
      setCustomerPin(null);
    }
  };
}
