export function useSimpleCheckoutRouteProps({
  canUseGuestCheckoutFlow = false,
  cart = [],
  cartCount = 0,
  checkoutError = '',
  checkoutLoading = false,
  checkoutResult = null,
  customerAddress = '',
  customerPin = null,
  DropdownComponent,
  fnbPaymentType = 'cash',
  fnbScheduledFor = '',
  fnbSpecialInstructions = '',
  goStoreCatalogPage,
  handleCheckout,
  handleDownloadCheckoutImage,
  handlePaymentTypeChange,
  handlePinMyLocation,
  handleQuote,
  isDeliveryOrder = false,
  isDesktopCheckout = false,
  isDgfyCustomerSignedIn = false,
  isMobileViewport = false,
  money,
  orderMethod = 'delivery',
  pinLocationError = '',
  pinLocationLoading = false,
  promoDiscountSummaryRow = null,
  quoteError = '',
  quoteResult = null,
  renderAccountOwnedIdentitySummary,
  renderCheckoutPromoStack,
  renderGuestCheckoutEntry,
  renderGuestIdentityFields,
  renderStorefrontClosedNotice,
  requireQuoteForCheckout = false,
  selectedLocation = null,
  selectedLocationId = null,
  selectedStore = null,
  servicesBodyFont,
  servicesDisplayFont,
  setCheckoutResult,
  setCustomerAddress,
  setCustomerPin,
  setFnbScheduledFor,
  setFnbSpecialInstructions,
  setOrderMethod,
  setPinLocationError,
  setSelectedLocationId,
  setSimpleOrderStep,
  simpleCheckoutAllowed = false,
  simpleCustomerStepComplete = false,
  simpleHasCustomerIdentity = false,
  simpleHasPrimaryIdentityContact = false,
  simpleOrderMethodOptions = [],
  simpleOrderStep = 1,
  simpleStepOneReady = false,
  storefrontClosedByHours = false,
  storeLocations = [],
  totalsForDisplay,
  withAssetOrigin
}) {
  return {
    canUseGuestCheckoutFlow,
    cart,
    cartCount,
    checkoutError,
    checkoutLoading,
    checkoutResult,
    customerAddress,
    customerPin,
    DropdownComponent,
    fnbPaymentType,
    fnbScheduledFor,
    fnbSpecialInstructions,
    isDeliveryOrder,
    isDesktopCheckout,
    isDgfyCustomerSignedIn,
    isMobileViewport,
    money,
    orderMethod,
    pinLocationError,
    pinLocationLoading,
    promoDiscountSummaryRow,
    quoteError,
    quoteResult,
    renderAccountOwnedIdentitySummary,
    renderCheckoutPromoStack,
    renderGuestCheckoutEntry,
    renderGuestIdentityFields,
    renderStorefrontClosedNotice,
    requireQuoteForCheckout,
    selectedLocation,
    selectedLocationId,
    selectedStore,
    servicesBodyFont,
    servicesDisplayFont,
    simpleCheckoutAllowed,
    simpleCustomerStepComplete,
    simpleHasCustomerIdentity,
    simpleHasPrimaryIdentityContact,
    simpleOrderMethodOptions,
    simpleOrderStep,
    simpleStepOneReady,
    storefrontClosedByHours,
    storeLocations,
    totalsForDisplay,
    withAssetOrigin,
    onBackToCatalog: goStoreCatalogPage,
    onCheckout: handleCheckout,
    onCustomerAddressChange: setCustomerAddress,
    onDownloadCheckoutImage: handleDownloadCheckoutImage,
    onOrderMethodChange: (nextOrderMethod) => {
      setOrderMethod(nextOrderMethod);
      setPinLocationError('');
    },
    onPaymentTypeChange: handlePaymentTypeChange,
    onPinChange: setCustomerPin,
    onPinClear: () => setCustomerPin(null),
    onPinMyLocation: handlePinMyLocation,
    onQuote: handleQuote,
    onScheduledForChange: setFnbScheduledFor,
    onSelectedLocationChange: setSelectedLocationId,
    onSetCheckoutResult: setCheckoutResult,
    onSetSimpleOrderStep: setSimpleOrderStep,
    onSpecialInstructionsChange: setFnbSpecialInstructions
  };
}
