/**
 * Shapes the existing shell/runtime dependencies into the F&B tracking route
 * presentation contract. It deliberately has no fetching or navigation logic.
 */
export function buildRetailTrackingRouteProps({
  canOpenTrackingDrawer,
  checkoutTab,
  copyTextToClipboard,
  formatTicketDate,
  getCompletedTrackingLabel,
  getTrackingFlowForOrderMethod,
  goStoreCatalogPage,
  goStoreOrderPage,
  isAccountTracking,
  isMobileViewport,
  isOpen,
  isStandaloneTrackingPage,
  money,
  onClose,
  openRetailItemReviewFromInvite,
  openFullTrackingForPin,
  primaryLocationId,
  routeSlug,
  selectedLocationId,
  selectedStore,
  selectedTrackingPin,
  servicesBodyFont,
  servicesDisplayFont,
  setCheckoutTab,
  showCompletedTrackingCard,
  storeLocations,
  storePath,
  tileTransformRequest,
  tilingServer,
  toSlug,
  trackingDrawerOrders,
  trackingError,
  trackingPinInput,
  trackingResult,
  withAssetOrigin,
}) {
  return {
    visible: checkoutTab === 'track',
    route: {
      displayFont: servicesDisplayFont,
      goStoreCatalogPage,
      isMobileViewport,
      routeSlug,
      selectedStore,
      storePath,
      toSlug,
      withAssetOrigin,
    },
    page: {
      actions: { copyTextToClipboard, goStoreCatalogPage, goStoreOrderPage, openRetailItemReviewFromInvite, setCheckoutTab },
      formatters: { formatTicketDate, money, servicesBodyFont, servicesDisplayFont, TILING_SERVER: tilingServer, tileTransformRequest },
      getCompletedTrackingLabel,
      getTrackingFlowForOrderMethod,
      isMobileViewport,
      presentation: {
        backLabel: 'Back to Items',
        returnToCatalog: true,
      },
      primaryLocationId,
      selectedLocationId,
      selectedStore,
      selectedTrackingPin,
      showCompletedTrackingCard,
      storeLocations,
      trackingError,
      trackingPinInput,
      trackingResult,
      withAssetOrigin,
    },
    drawer: {
      canOpen: canOpenTrackingDrawer && !isStandaloneTrackingPage,
      isAccountTracking,
      isMobileViewport,
      isOpen,
      money,
      onClose,
      openFullTrackingForPin,
      orders: trackingDrawerOrders,
      selectedStore,
      withAssetOrigin,
    },
  };
}
