import React, { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import api from '../src/services/api.js';
import { dgfyAuthHeader, fetchDgfyLegalTerms, getStoredDgfyToken, startDgfyTenantSession } from '../src/services/dgfyAuthService.js';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { WORKFLOW_MODE_SELECT_VALUES } from '../src/features/settings/workflowMode.js';

const COPY = { pending_review: ['Waiting for approval', 'Your company registration is waiting for Platform Admin approval. Please check the email you used for DGFY registration.'], setting_up_company: ['Setting up your company', 'Your registration was approved and your company is being set up.'], ready: ['Your company is ready', 'Your company is ready. Select Continue when you are ready to open it.'], setup_delayed: ['Setup delayed', 'Your registration is approved, but setup needs a retry. A Platform Admin has been notified.'], rejected: ['Registration needs changes', 'Review the reason below, then correct and resubmit your registration.'] };

export default function CompanyRegistrationStatus() {
  const { applicationId } = useParams(); const navigate = useNavigate();
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [resubmitting, setResubmitting] = useState(false); const [editingRejected, setEditingRejected] = useState(false); const [legalTerms, setLegalTerms] = useState(null); const [resubmitForm, setResubmitForm] = useState({ name: '', workflowMode: '', industryTag: '', acceptedCompanyTerms: false });
  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await api.get(`/dgfy/company-registration/${encodeURIComponent(applicationId)}`, { withCredentials: true, skipTenantAuthHeaders: true, headers: dgfyAuthHeader(getStoredDgfyToken()) }); const next = response.data?.data || null; setData(next); if (next?.editable_submission) setResubmitForm((current) => ({ ...current, name: next.editable_submission.company_name || '', workflowMode: next.editable_submission.workflow_mode || '', industryTag: next.editable_submission.industry_tag || '' })); } catch (err) { setError(err.response?.data?.message || 'Unable to load this registration status. Sign in with the DGFY account that submitted it.'); } finally { setLoading(false); } }, [applicationId]);
  useEffect(() => { let active = true; api.get(`/dgfy/company-registration/${encodeURIComponent(applicationId)}`, { withCredentials: true, skipTenantAuthHeaders: true, headers: dgfyAuthHeader(getStoredDgfyToken()) }).then((response) => { if (!active) return; const next = response.data?.data || null; setData(next); if (next?.editable_submission) setResubmitForm((current) => ({ ...current, name: next.editable_submission.company_name || '', workflowMode: next.editable_submission.workflow_mode || '', industryTag: next.editable_submission.industry_tag || '' })); }).catch((err) => { if (active) setError(err.response?.data?.message || 'Unable to load this registration status. Sign in with the DGFY account that submitted it.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [applicationId]);
  useEffect(() => { let active = true; fetchDgfyLegalTerms().then((terms) => { if (active) setLegalTerms(terms); }).catch(() => { if (active) setLegalTerms(null); }); return () => { active = false; }; }, []);
  const resubmit = async () => { setResubmitting(true); setError(''); try { const snapshot = legalTerms?.flows?.company_registration?.snapshot || {}; await api.post(`/dgfy/company-registration/${encodeURIComponent(applicationId)}/resubmit`, { name: resubmitForm.name, workflowMode: resubmitForm.workflowMode, industryTag: resubmitForm.industryTag, accepted_company_terms: resubmitForm.acceptedCompanyTerms, company_terms_version: snapshot.company_terms_version, marketplace_terms_version: snapshot.marketplace_terms_version }, { withCredentials: true, skipTenantAuthHeaders: true, headers: dgfyAuthHeader(getStoredDgfyToken()) }); setEditingRejected(false); await load(); } catch (err) { setError(err.response?.data?.message || 'Unable to resubmit this registration.'); } finally { setResubmitting(false); } };
  const continueToCompany = async () => { if (!data?.tenant_id) return; setError(''); setResubmitting(true); try { await startDgfyTenantSession({ tenantId: data.tenant_id }); navigate('/'); } catch (err) { setError(err.response?.data?.message || 'Your company is ready, but the secure session could not be started. Try again from this status page.'); } finally { setResubmitting(false); } };
  if (loading) return <main className="mx-auto max-w-xl p-8">Loading registration status…</main>;
  if (error) return <main className="mx-auto max-w-xl p-8 text-red-700">{error}</main>;
  const [title, body] = COPY[data?.status] || COPY.pending_review;
  return <main className="mx-auto max-w-xl p-6 sm:p-10"><section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-medium text-slate-500">DGFY company registration</p><h1 className="mt-2 text-2xl font-bold text-slate-900">{title}</h1><p className="mt-3 text-slate-600">{body}</p><dl className="mt-6 space-y-2 rounded-xl bg-slate-50 p-4 text-sm"><div><dt className="text-slate-500">Company</dt><dd className="font-medium">{data.company_name}</dd></div><div><dt className="text-slate-500">Registration email</dt><dd>{data.registration_email_masked}</dd></div></dl>{data.rejection_reason && <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Reason:</strong> {data.rejection_reason}</div>}{data.status === 'rejected' && editingRejected && <form onSubmit={(event) => { event.preventDefault(); void resubmit(); }} className="mt-5 space-y-3 rounded-xl border bg-slate-50 p-4"><h2 className="font-semibold text-slate-900">Correct and resubmit</h2><Input required value={resubmitForm.name} onChange={(event) => setResubmitForm({ ...resubmitForm, name: event.target.value })} placeholder="Company name"/><select required className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={resubmitForm.workflowMode} onChange={(event) => setResubmitForm({ ...resubmitForm, workflowMode: event.target.value })}><option value="">Select business industry</option>{WORKFLOW_MODE_SELECT_VALUES.map((mode) => <option key={mode} value={mode}>{mode.replace(/_/g, ' ')}</option>)}</select><Input value={resubmitForm.industryTag} onChange={(event) => setResubmitForm({ ...resubmitForm, industryTag: event.target.value })} placeholder="Optional industry detail"/><label className="flex gap-2 text-sm text-slate-700"><input required type="checkbox" checked={resubmitForm.acceptedCompanyTerms} onChange={(event) => setResubmitForm({ ...resubmitForm, acceptedCompanyTerms: event.target.checked })} disabled={!legalTerms}/><span>I accept the current DGFY company and marketplace terms.</span></label><div className="flex gap-2"><Button disabled={resubmitting || !legalTerms} type="submit">{resubmitting ? 'Resubmitting…' : 'Resubmit for review'}</Button><Button type="button" variant="outline" onClick={() => setEditingRejected(false)}>Cancel</Button></div></form>}<div className="mt-6 flex flex-wrap gap-3"><Button type="button" variant="outline" onClick={() => void load()}>Refresh</Button>{data.status === 'rejected' && !editingRejected && <Button type="button" onClick={() => setEditingRejected(true)}>Edit and resubmit</Button>}{data.status === 'ready' && <Button type="button" onClick={() => void continueToCompany()} disabled={resubmitting}>{resubmitting ? 'Opening…' : 'Continue to company'}</Button>}<Button asChild variant="link"><Link to="/dgfy/account">DGFY Account</Link></Button></div></section></main>;
}
