import { useMemo } from 'react';

export function useCustomerDashboardStorefrontBridge({
  accountIdentityInitials,
  accountIdentityName,
  accountIdentityContact,
  accountPanel,
  hasSavedCustomerDetails,
  maskedSavedCustomerPreview,
  activeCustomerOrders,
  activeCustomerOrderCount,
  trackedCustomerActivity,
  customerTrackLoadingReference,
  customerTrackError,
  accountOrderActionReference,
  accountAddressActionId,
  accountPayoutActionId,
  accountCashoutActionId,
  handleLoadAccountPanel,
  handleGetCustomerOrderDetails,
  handleTrackCustomerReference,
  handleMarkNotificationRead,
  handleMarkAllNotificationsRead,
  handleStorefrontSignOut,
  openBusinessRegistrationFlow,
  requestDgfyBusinessSecurityCode,
  handleAcceptDgfyCompanyInvitation,
  handleRejectDgfyCompanyInvitation,
  handleLeaveDgfyCompany,
  switchDgfyCompanyFromStorefront,
  clearSavedCustomerDetailsForDevice,
  useAccountAddressForCheckout,
  handleSaveAccountAddress,
  handleDeleteAccountAddress,
  handleSetDefaultAccountAddress,
  renderAddressPinEditor,
  handleSavePayoutMethod,
  handleDeletePayoutMethod,
  handleSetDefaultPayoutMethod,
  handleRequestCashout,
  handleCancelCashout,
  openStorefrontFromAccountEntry,
  submitAccountReviewFromDashboard,
  handleOpenBusinessInventory,
  handleOpenBusinessPos,
  getOwnBusinessDayCloseStatus,
  configureOwnBusinessDayClosePin,
  resolveStorefrontMetaForAccountEntry,
  withAssetOrigin,
  savedCustomerDetails,
  applySavedCustomerDetails,
  closeAccountDrawer,
  openCanonicalDgfyAuth
}) {
  const sources = useMemo(() => ({
    accountIdentityInitials,
    accountIdentityName,
    accountIdentityContact,
    accountPanel,
    hasSavedCustomerDetails,
    maskedSavedCustomerPreview,
    activeCustomerOrders,
    activeCustomerOrderCount,
    trackedCustomerActivity,
    customerTrackLoadingReference,
    customerTrackError,
    accountOrderActionReference,
    accountAddressActionId,
    accountPayoutActionId,
    accountCashoutActionId,
    handleLoadAccountPanel,
    handleGetCustomerOrderDetails,
    handleTrackCustomerReference,
    handleMarkNotificationRead,
    handleMarkAllNotificationsRead,
    handleStorefrontSignOut,
    openBusinessRegistrationFlow,
    requestDgfyBusinessSecurityCode,
    handleAcceptDgfyCompanyInvitation,
    handleRejectDgfyCompanyInvitation,
    handleLeaveDgfyCompany,
    switchDgfyCompanyFromStorefront,
    clearSavedCustomerDetailsForDevice,
    useAccountAddressForCheckout,
    handleSaveAccountAddress,
    handleDeleteAccountAddress,
    handleSetDefaultAccountAddress,
    renderAddressPinEditor,
    handleSavePayoutMethod,
    handleDeletePayoutMethod,
    handleSetDefaultPayoutMethod,
    handleRequestCashout,
    handleCancelCashout,
    openStorefrontFromAccountEntry,
    submitAccountReviewFromDashboard,
    handleOpenBusinessInventory,
    handleOpenBusinessPos,
    getOwnBusinessDayCloseStatus,
    configureOwnBusinessDayClosePin,
    resolveStorefrontMetaForAccountEntry,
    withAssetOrigin
  }), [
    accountAddressActionId,
    accountCashoutActionId,
    accountIdentityContact,
    accountIdentityInitials,
    accountIdentityName,
    accountOrderActionReference,
    accountPanel,
    accountPayoutActionId,
    activeCustomerOrderCount,
    activeCustomerOrders,
    clearSavedCustomerDetailsForDevice,
    customerTrackError,
    customerTrackLoadingReference,
    handleAcceptDgfyCompanyInvitation,
    handleCancelCashout,
    handleDeleteAccountAddress,
    handleDeletePayoutMethod,
    handleLeaveDgfyCompany,
    handleLoadAccountPanel,
    handleGetCustomerOrderDetails,
    handleMarkAllNotificationsRead,
    handleMarkNotificationRead,
    handleOpenBusinessInventory,
    handleOpenBusinessPos,
    getOwnBusinessDayCloseStatus,
    configureOwnBusinessDayClosePin,
    handleRejectDgfyCompanyInvitation,
    handleRequestCashout,
    handleSaveAccountAddress,
    handleSavePayoutMethod,
    handleSetDefaultAccountAddress,
    handleSetDefaultPayoutMethod,
    handleStorefrontSignOut,
    handleTrackCustomerReference,
    hasSavedCustomerDetails,
    maskedSavedCustomerPreview,
    openBusinessRegistrationFlow,
    openStorefrontFromAccountEntry,
    renderAddressPinEditor,
    requestDgfyBusinessSecurityCode,
    resolveStorefrontMetaForAccountEntry,
    submitAccountReviewFromDashboard,
    switchDgfyCompanyFromStorefront,
    trackedCustomerActivity,
    useAccountAddressForCheckout,
    withAssetOrigin
  ]);

  const guestAuth = useMemo(() => ({
    savedCustomerDetails,
    hasSavedCustomerDetails,
    onContinueAsGuest: () => {
      if (hasSavedCustomerDetails) {
        applySavedCustomerDetails();
      }
      closeAccountDrawer();
    },
    onClearSavedDetails: clearSavedCustomerDetailsForDevice,
    onOpenAuth: () => {
      closeAccountDrawer();
      openCanonicalDgfyAuth('customer');
    },
    onOpenRegisterBusiness: () => {
      closeAccountDrawer();
      openBusinessRegistrationFlow();
    }
  }), [
    applySavedCustomerDetails,
    clearSavedCustomerDetailsForDevice,
    closeAccountDrawer,
    hasSavedCustomerDetails,
    openBusinessRegistrationFlow,
    openCanonicalDgfyAuth,
    savedCustomerDetails
  ]);

  return useMemo(
    () => ({
      sources,
      guestAuth
    }),
    [guestAuth, sources]
  );
}

export default useCustomerDashboardStorefrontBridge;
