export function buildServicesTrackingRouteProps({
  accountIdentityInitials,
  accountIdentityName,
  accountIdentityRawEmail,
  advanceServicesLocalTracking,
  servicesBodyFont,
  servicesDisplayFont,
  servicesPrimary,
  servicesPrimaryBorder,
  servicesPrimaryDark,
  servicesPrimarySoft,
  catalog,
  copyTextToClipboard,
  formatTicketDate,
  goStoreCatalogPage,
  goStoreTrackPage,
  handleTrack,
  isMobileViewport,
  isTrackingRefreshing,
  money,
  openAccountPanel,
  selectedLocation,
  selectedStore,
  serviceHandoff = 'delivery',
  setTrackingPinInput,
  tileTransformRequest,
  tilingServer,
  trackingError,
  trackingPinInput,
  trackingResult,
  withAssetOrigin
}) {
  const trackingPin = String(trackingResult?.tracking_pin || trackingPinInput || '').trim().toUpperCase();
  return {
    frame: {
      accountIdentityInitials,
      accountIdentityName,
      accountIdentityRawEmail,
      bodyFont: servicesBodyFont,
      displayFont: servicesDisplayFont,
      goStoreCatalogPage,
      goStoreTrackPage,
      isMobileViewport,
      openAccountPanel,
      selectedLocation,
      selectedStore,
      serviceHandoff,
      trackingPin,
      tileTransformRequest,
      tilingServer,
      withAssetOrigin
    },
    page: {
  actions: {
    copyTextToClipboard,
    goStoreCatalogPage,
    handleTrack,
    money,
    setTrackingPinInput,
    advanceLocalSimulation: advanceServicesLocalTracking
  },
      catalog,
      formatTicketDate,
      bodyFont: servicesBodyFont,
      displayFont: servicesDisplayFont,
      isMobileViewport,
      isTrackingRefreshing,
      selectedStore,
      serviceHandoff,
      servicesPrimary,
      servicesPrimaryBorder,
      servicesPrimaryDark,
      servicesPrimarySoft,
      trackingError,
      trackingPinInput,
      trackingResult,
      tileTransformRequest,
      tilingServer
    }
  };
}
