import { DataTypes } from 'sequelize';

export default (sequelize) => sequelize.define('TenantRevenueTransaction', {
  revenue_transaction_id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  tenant_id: { type: DataTypes.UUID, allowNull: false },
  payment_session_id: { type: DataTypes.INTEGER, allowNull: false },
  policy_id: { type: DataTypes.BIGINT, allowNull: true },
  company_id: DataTypes.STRING(120),
  branch_id: DataTypes.STRING(120),
  order_id: DataTypes.STRING(120),
  provider: { type: DataTypes.STRING(40), allowNull: false, defaultValue: 'paymongo' },
  provider_payment_id: { type: DataTypes.STRING(120), allowNull: false },
  provider_payment_intent_id: DataTypes.STRING(120),
  provider_source_id: DataTypes.STRING(120),
  provider_balance_transaction_id: DataTypes.STRING(120),
  payment_method: DataTypes.STRING(60),
  currency: { type: DataTypes.STRING(3), allowNull: false, defaultValue: 'PHP' },
  gross_amount_centavos: { type: DataTypes.BIGINT, allowNull: false },
  provider_fee_centavos: DataTypes.BIGINT,
  provider_fee_vat_centavos: DataTypes.BIGINT,
  provider_net_centavos: DataTypes.BIGINT,
  provider_fee_source: { type: DataTypes.ENUM('webhook', 'api', 'statement', 'fallback', 'manual_review'), allowNull: false },
  dgfy_rate_bps: { type: DataTypes.INTEGER, allowNull: false },
  dgfy_fee_centavos: { type: DataTypes.BIGINT, allowNull: false },
  tenant_provider_fee_centavos: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
  dgfy_provider_fee_centavos: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
  refund_centavos: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
  chargeback_centavos: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
  adjustment_centavos: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
  tenant_net_payable_centavos: { type: DataTypes.BIGINT, allowNull: false },
  settlement_cycle_days: { type: DataTypes.INTEGER, allowNull: false },
  eligibility_at: { type: DataTypes.DATE, allowNull: false },
  fulfillment_status: {
    type: DataTypes.ENUM('pending', 'completed', 'rejected', 'cancelled'),
    allowNull: false,
    defaultValue: 'pending'
  },
  fulfilled_at: DataTypes.DATE,
  fulfillment_updated_at: DataTypes.DATE,
  payment_status: { type: DataTypes.ENUM('paid', 'partially_refunded', 'refunded', 'chargeback', 'reversed'), allowNull: false },
  reconciliation_status: { type: DataTypes.ENUM('pending', 'reconciled', 'exception', 'approved_override'), allowNull: false },
  settlement_status: { type: DataTypes.ENUM('pending', 'eligible', 'scheduled', 'processing', 'partially_settled', 'settled', 'on_hold', 'reversed'), allowNull: false },
  provider_event_id: DataTypes.STRING(160),
  paid_at: { type: DataTypes.DATE, allowNull: false },
  financial_snapshot: { type: DataTypes.JSON, allowNull: false },
  created_by: { type: DataTypes.STRING(120), allowNull: false },
  approved_by: DataTypes.STRING(120)
}, { tableName: 'tenant_revenue_transactions', timestamps: true, createdAt: 'created_at', updatedAt: 'updated_at' });
