// Plain pass-through props bundle for RetailOrderPage. Real, already-existing shared state is
// threaded through here: cart display, store info, navigation, viewport, the shared
// guest/DGFY-account identity + guest email OTP infrastructure (useGuestCustomerIdentity.js,
// useFnbGuestCheckoutOtp.js), and the shared saved-address/map-pin infrastructure
// (useSignedInCheckoutAddresses.js, useDeliveryPinResolution.js) — all instantiated once in
// StorefrontApp.jsx and already consumed by F&B/MSME. Schedule mode/time and special
// instructions remain intentionally local state owned by RetailOrderPage itself, since neither
// is wired to the backend yet. Retail-only — the other default-like workflow modes keep using
// useDefaultOrderPageProps.js unmodified.
export function useRetailOrderPageProps({
  canAddPinnedLocation,
  canUseGuestCheckoutFlow,
  cart,
  cartCount,
  cartImageErrors,
  customerEmail,
  customerName,
  customerPhone,
  customerPin,
  deliveryLocationAction,
  deliveryLocationDisplayAddress,
  deliverySavedLocations,
  goStoreCatalogPage,
  guestCheckoutOtpCode,
  guestCheckoutOtpCooldownLabel,
  guestCheckoutOtpError,
  guestCheckoutOtpLoading,
  guestCheckoutOtpVerified,
  handleAddPinnedLocation,
  handleApplyGuestDetailsAndRequestOtp,
  handleGuestCheckoutOtpCodeChange,
  handlePinMyLocation,
  handleRequestGuestCheckoutOtp,
  handleVerifyGuestCheckoutOtp,
  applySavedDeliveryLocation,
  isDesktopCheckout,
  isDgfyCustomerSignedIn,
  isGuestCheckoutOtpCooldownActive,
  isMobileViewport,
  money,
  orderMethod,
  promoDiscountSummaryRow,
  pinLocationError,
  pinLocationLoading,
  renderAccountOwnedIdentitySummary,
  renderGuestCheckoutEntry,
  renderGuestIdentityFields,
  renderPromoCodePanel,
  renderStorefrontClosedNotice,
  selectedStore,
  selectedSavedLocationId,
  servicesBodyFont,
  servicesDisplayFont,
  setCartImageErrors,
  setCustomerPin,
  setDeliveryLocationAction,
  setOrderMethod,
  setPinLocationError,
  setResolvedDeliveryAddress,
  setSelectedSavedLocationId,
  setShowExpandedDeliveryMap,
  showExpandedDeliveryMap,
  storefrontClosedByHours,
  totalsForDisplay,
  withAssetOrigin,
  handleCheckout,
  checkoutLoading,
  checkoutError
}) {
  return {
    canAddPinnedLocation,
    canUseGuestCheckoutFlow,
    cart,
    cartCount,
    cartImageErrors,
    customerEmail,
    customerName,
    customerPhone,
    customerPin,
    deliveryLocationAction,
    deliveryLocationDisplayAddress,
    deliverySavedLocations,
    guestCheckoutOtpCode,
    guestCheckoutOtpCooldownLabel,
    guestCheckoutOtpError,
    guestCheckoutOtpLoading,
    guestCheckoutOtpVerified,
    handleAddPinnedLocation,
    handleApplyGuestDetailsAndRequestOtp,
    handleGuestCheckoutOtpCodeChange,
    handlePinMyLocation,
    handleRequestGuestCheckoutOtp,
    handleVerifyGuestCheckoutOtp,
    isDesktopCheckout,
    isDgfyCustomerSignedIn,
    isGuestCheckoutOtpCooldownActive,
    isMobileViewport,
    money,
    onSelectAddress: applySavedDeliveryLocation,
    orderMethod,
    promoDiscountSummaryRow,
    pinLocationError,
    pinLocationLoading,
    renderAccountOwnedIdentitySummary,
    renderGuestCheckoutEntry,
    renderGuestIdentityFields,
    renderPromoCodePanel,
    renderStorefrontClosedNotice,
    selectedStore,
    selectedSavedLocationId,
    servicesBodyFont,
    servicesDisplayFont,
    setCustomerPin,
    setDeliveryLocationAction,
    setOrderMethod,
    setPinLocationError,
    setResolvedDeliveryAddress,
    setSelectedSavedLocationId,
    setShowExpandedDeliveryMap,
    showExpandedDeliveryMap,
    storefrontClosedByHours,
    totalsForDisplay,
    withAssetOrigin,
    checkoutLoading,
    checkoutError,
    onBackToCatalog: goStoreCatalogPage,
    onCheckout: handleCheckout,
    onImageError: (itemId) => {
      const normalizedLineItemId = Number(itemId);
      if (!Number.isFinite(normalizedLineItemId)) return;
      setCartImageErrors((previous) => new Set([...previous, normalizedLineItemId]));
    }
  };
}
